### ISSUE TITLE
[Request] furry trigger case-sensitive

### ISSUE THREAD

**Issue by MooMooMatrix** [inkthought-labs/honkers#3]
furry is case sensitive

1. type 'Furry'

OMG THERE'S A FURRY!
OMG THERE'S A FURRY!
OMG THERE'S A FURRY!

**additional context**
any other things you need to add?
stinkys

**Comment by flarely** [comment]
This is a feature request, will be added in version 4.4-4.6.

**Comment by LakeTheEevee** [comment]
why am i not assigned

**Comment by flarely** [comment]
> why am i not assigned
you're not a dev...

**Comment by flarely** [comment]
@MooMooMatrix feature implemented, added in version 2.4.4.
