### ISSUE TITLE
Furry thing, I don't know how to name it fu-

### ISSUE THREAD

**Issue by Paciic** [inkthought-labs/honkers#5]
**describe the issue**
So the 'furry' response works at #bonk at headway.

**how do you reproduce the issue?**
1. Type furry in #bonk at headway
2. Result
3. Type furry in #bonk at inkthought
4. Nothing happens, message gets deleted
5.

**normally, what happens?**
See above

**screenshots**
![D8F1C724-C4BA-4430-A867-B8A1CE42DD81](https://user-images.githubusercontent.com/70255895/92294411-9391ed80-ef5e-11ea-96e2-b0f1e093b265.png)

**additional context**
any other things you need to add?
no

**Comment by flarely** [comment]
reopen this

**Comment by flarely** [comment]
working on it s0n

**Comment by ItsJasperHere** [comment]
not possible without modifying bonkers code.

**Comment by ItsJasperHere** [comment]
Flare fucking make a private bonkers repo you shit

**Comment by flarely** [comment]
> Flare fucking make a private bonkers repo you shit

ITS POSSIBLE. Just modify it so that honkers will not reply to furries inside #bonk

**Comment by ItsJasperHere** [comment]
> > Flare fucking make a private bonkers repo you shit
> 
> ITS POSSIBLE. Just modify it so that honkers will not reply to furries inside #bonk
oh you want it not respond?
alright that's easy not at home tho
will do before tonight

**Comment by flarely** [comment]
> > > Flare fucking make a private bonkers repo you shit
> 
> > 
> 
> > ITS POSSIBLE. Just modify it so that honkers will not reply to furries inside #bonk
> 
oh you want it not respond?
alright that's easy not at home tho will do before tonight

Thanks jasper

**Comment by flarely** [comment]
I've just wrote a beta version, haven't been pushed to the bot yet, @ItsJasperHere please review

**Comment by flarely** [comment]
Alright! It's been pushed and it's now working. Closed.
