### ISSUE TITLE
Month long delayed project: Flonkers and Quackers

### ISSUE THREAD

**Issue by Paciic** [inkthought-labs/honkers#6]
**is this related to bugs? if yes, please open a bug report issue.**

**what do you want to see added?**
 Make Flonkers and Quackers

**what alternatives did you try?**

**additional information**
https://discord.com/channels/693044826492633149/740513189342609428/740513366476456037

**Comment by flarely** [comment]
We're working on some more major projects rn... but sure. Will add once performance updates are done.

**Comment by flarely** [comment]
honestly... i don't think this would be really great. it would literally just bloat the bot as a whole and completely slow it down. i think quacking and flonking don't really represent a goose. maybe in the future?
