### ISSUE TITLE
h0nk

### ISSUE THREAD

**Issue by Paciic** [inkthought-labs/honkers#8]
**is this related to bugs? if yes, please open a bug report issue.**

**what do you want to see added?**
a very small chance (1-5%) of getting h0nk when Honking in #honk

**what alternatives did you try?**
Um what?

**additional information**
HONK

**Comment by flarely** [comment]
This would be pretty hard to make. In the future...

**Comment by ItsJasperHere** [comment]
w h y

**Comment by ItsJasperHere** [comment]
should be easy enough, just do a math random thing

**Comment by flarely** [comment]
Implemented in 2.7.1 - you'll have a 5% chance to get the h0nk response!
